import Head from 'next/head';
import Header from '@components/Header';
import Contact from '@components/Contact';
import About from '@components/About';
import Projects from '@components/Projects';
import Nav from '@components/Nav';
import Footer from '@components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>David&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <Projects />
      <About />
      <Contact />
      <Footer />
    </>
  );
}
