import Head from 'next/head';
import imgPerson from '@images/person_programming.jpg';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>David&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.Home}>
        <p>
          <span className={styles['Home__hello']}>Hola, soy David, FullStack Web Developer </span>
          <br />
          FullStack JavaScript. En busca del desarrollo profesional
        </p>
        <img src={imgPerson.src} alt="person programming" />
      </section>
    </>
  );
}
